### ISSUE TITLE
Hello and thanks for sharing the code

### ISSUE THREAD

**Issue by dvision1979** [tan-tan-kanarek/kaltura-ad-server#1]
Would it be possible to put together a small set of instructions on how to install and run this piece of software?
Thank you!

Regards,
Dan

**Comment by tan-tan-kanarek** [comment]
Hi Dan,
This code was written in order to test VAST functionality against basic server.
You can use test.js as example, just configure the partner-id and secret of your Kaltura account.

**Comment by tan-tan-kanarek** [comment]
Continued in https://github.com/tan-tan-kanarek/kaltura-ad-server/issues/2
